### ISSUE TITLE
关于attention

### ISSUE THREAD

**Issue by zxbnmop** [wenyu332/daguan_bert_ner#21]
您好，我想试着在lstm_out那里加一层attention，attention层该怎么接入呢？试着写了一个attention层，代码能跑通，loss正常下降，但是f1值都是0。
<img width="619" alt="1" src="https://user-images.githubusercontent.com/21164995/63908296-4462d400-ca51-11e9-916d-0b614f6cd54d.png">

**Comment by wenyu332** [comment]
我想你大概忘记写mask了。。
